# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту denisill@mail.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -denisill@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

# Используем ключ с сайта https://codecov.io/
env:
  global:
    - CODECOV_TOKEN="86160488-d8c0-4bf8-805b-15941b49c6de"